version: '3.8'

services:
  nodeapp:
    build: .
    container_name: nodeapp
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    command: npm start
